name: 用户词汇反馈
description: 提交您希望加入词库的词汇
title: "[反馈]: "
labels: ["feedback-word"]
assignees:
  - your-github-username

body:
  - type: input
    id: word
    attributes:
      label: 反馈词汇
      description: 请输入一个词汇
      placeholder: 例如：四十码
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 使用场景
      description: 请描述此词汇的使用背景（可选）
      placeholder: 例如：服装尺码输入常用
    validations:
      required: false
